TOXIC_TERMS = {
    "nefret",
    "aptal",
    "gerizeka",
    "gerizekâ",
    "salak",
    "tehdit",
    "öldür",
    "oldur",
    "siddet",
    "şiddet",
    "hakaret",
    "irkci",
    "ırkçı",
    "asagila",
    "aşağila",
    "aşağıla",
    "gerizekalı",
    "kahpe",
    "pislik",
    "ezik",
    "amk", "aq", "mk", "sik", "siktir", "sikeyim", "orospu",
    "orospucocu", "orospuçocuğu", "piç", "ibne", "yarrak", "göt",
    "pezevenk", "geber",
}

SPAM_TERMS = {
    "bedava",
    "hemen kazan",
    "tikla",
    "tıkla",
    "inanilmaz firsat",
    "inanılmaz fırsat",
    "garanti kazanc",
    "garanti kazanç",
    "takip et kazan",
    "dm at",
    "link bio",
    "kaçırma",
    "son dakika fırsat",
    "kredi kart",
}

FOCUS_TERMS = {
    "odak",
    "pomodoro",
    "derin calisma",
    "derin çalışma",
    "plan",
    "rutin",
    "sessiz",
    "dikkat",
    "verimli",
    "adim adim",
    "adım adım",
    "checklist",
    "nefes",
    "denge",
    "molası",
    "mola",
    "bildirim",
    "kesintisiz",
    "görev",
}

LEARN_TERMS = {
    "ogren",
    "öğren",
    "egitim",
    "eğitim",
    "neden",
    "nasil",
    "nasıl",
    "acikla",
    "açıkla",
    "arastir",
    "araştır",
    "bilim",
    "model",
    "veri",
    "kanit",
    "kanıt",
    "ornek",
    "örnek",
    "tanım",
    "tanim",
    "kaynak",
    "ders",
    "kavram",
    "yöntem",
    "analiz",
}

FUN_TERMS = {
    "eglence",
    "eğlence",
    "komik",
    "mizah",
    "hafta sonu",
    "keyif",
    "oyun",
    "film",
    "muzik",
    "müzik",
    "sohbet",
    "arkadas",
    "arkadaş",
    "guldur",
    "güldür",
    "albüm",
    "kahve",
    "yürüyüş",
}

QUALITY_MARKERS = {
    "cunku",
    "çünkü",
    "ancak",
    "bu nedenle",
    "ornek",
    "örnek",
    "ozetle",
    "özetle",
    "adim",
    "adım",
    "bu yüzden",
    "dolayısıyla",
    "öte yandan",
}
